### ISSUE TITLE
Feature request: Generate partial validation method

### ISSUE THREAD

**Issue by harrison314** [martinothamar/WrapperValueObject#5]
It would be appropriate to generate partial methods for the validation of the value.

Code:
```cs
[WrapperValueObject(typeof(decimal))] readonly partial struct Money { }
```

Generates eg.:
```cs
partial struct Money 
{
    private decimal _value;

    
    public Money(decimal value)
    {
         Validate(value);
         _value = value;
    } 

   partial void Validate(decimal value);
   // ...
}
```

And if the consumer of api will want to implement value check/validation, then implements method _Validate_.

```cs
[WrapperValueObject(typeof(decimal))] 
readonly partial struct Money 
{
    partial void Validate(decimal value)
    {
         if(value<0.0) throw new ArgumentException("Money value can not by less than zero.");
    }
 }
```

Use cases:
 - Databse IDs (must by more than zero),
 - String keys in specific format (for nosql databases),
 - Percent (0-100%),
 - Special units (PH, °C,...)

**Comment by martinothamar** [comment]
Very good point, would like to support this. Do you have time for a PR? If not I can probably give it a shot this weekend. Thanks!
